/**
 * @description TabbarChange 事件
 * **/
export const TABBAR_CHANGE = 'TABBAR_CHANGE';

/**
 * @description POSITION_MODULE 区位模块展示事件
 * **/
export const POSITION_MODULE_SHOW = "POSITION_MODULE_SHOW";



/**
 * @description BLUEPRINT_MODULE_SHOW_HOUSE_APPRECIATION 户型鉴赏 - 显示尺寸
 * **/
export const BLUEPRINT_MODULE_SHOW_HOUSE_APPRECIATION = "BLUEPRINT_MODULE_SHOW_HOUSE_APPRECIATION";
/**
 * @description BLUEPRINT_MODULE_SHOW_PRESENT 户型鉴赏 - 显示赠送面积
 * **/
export const BLUEPRINT_MODULE_SHOW_PRESENT = "BLUEPRINT_MODULE_SHOW_PRESENT";
/**
 * @description BLUEPRINT_MODULE_SHOW_VENTILATE 户型鉴赏 - 通风演示
 * **/
export const BLUEPRINT_MODULE_SHOW_VENTILATE = "BLUEPRINT_MODULE_SHOW_VENTILATE";
/**
 * @description BLUEPRINT_MODULE_SHOW_GLITTERING 户型鉴赏 - 亮点
 * **/
export const BLUEPRINT_MODULE_SHOW_GLITTERING = "BLUEPRINT_MODULE_SHOW_GLITTERING";
/**
 * @description BLUEPRINT_MODULE_SHOW_DIRECTION 户型鉴赏 - 朝向
 * **/
export const BLUEPRINT_MODULE_SHOW_DIRECTION = "BLUEPRINT_MODULE_SHOW_DIRECTION";